# Generated by Django 5.2.13 on 2026-04-14 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_model'),
        ('customers', '0002_remove_customer_email_customer_business_number_and_more'),
        ('invoices', '0004_invoice_car_info_invoice_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='work_order_close_date',
            new_name='last_edit_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='cars.car'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('cancelled', 'Cancelled')], default='final', max_length=20),
        ),
    ]
