# Generated by Django 5.2.13 on 2026-04-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_rename_work_order_close_date_invoice_last_edit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('cancelled', 'Cancelled')], default='final', max_length=20),
        ),
    ]
