# Generated by Django 5.2.13 on 2026-05-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_po_number_alter_invoice_status'),
        ('invoices', '0006_invoice_email_sent'),
    ]

    operations = [
    ]
